# Generated by Django 5.1 on 2024-08-21 05:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50)),
                ('afa_case_id', models.CharField(max_length=10)),
                ('line_name', models.CharField(max_length=20)),
                ('no_of_terminals', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2)])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_accessed_on', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('cfg_file', models.FileField(upload_to='comtrade/files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cfg'])])),
                ('dat_file', models.FileField(upload_to='comtrade/files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['dat'])])),
                ('station_name', models.CharField(max_length=20, null=True)),
                ('analog_channel_count', models.PositiveSmallIntegerField(null=True)),
                ('digital_channel_count', models.PositiveSmallIntegerField(null=True)),
                ('start_time_stamp', models.DateTimeField(null=True)),
                ('trigger_time_stamp', models.DateTimeField(null=True)),
                ('line_frequency', models.PositiveSmallIntegerField(null=True)),
                ('sampling_frequency', models.PositiveSmallIntegerField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='comtrade_reader.project')),
            ],
        ),
        migrations.CreateModel(
            name='AnalogChannels',
            fields=[
                ('comtrade_channel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('phase', models.CharField(max_length=5)),
                ('unit', models.CharField(max_length=5)),
                ('primary', models.PositiveSmallIntegerField()),
                ('secondary', models.PositiveSmallIntegerField()),
                ('signal', models.CharField(choices=[('Ia', 'Phase A current'), ('Ib', 'Phase B current'), ('Ic', 'Phase C current'), ('Va', 'Phase A voltage'), ('Vb', 'Phase B voltage'), ('Vc', 'Phase C voltage'), ('-', 'None')], default='-', max_length=2)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_channels', to='comtrade_reader.file')),
            ],
            options={
                'unique_together': {('file', 'comtrade_channel_id')},
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['line_name'], name='comtrade_re_line_na_9b1294_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['station_name'], name='comtrade_re_station_342026_idx'),
        ),
    ]
