# Generated by Django 5.1 on 2024-08-21 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalogChannels',
        ),
    ]
