# Generated by Django 5.1 on 2024-08-21 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0002_delete_analogchannels'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalogChannel',
            fields=[
                ('comtrade_channel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('phase', models.CharField(max_length=5)),
                ('unit', models.CharField(max_length=5)),
                ('primary', models.PositiveSmallIntegerField()),
                ('secondary', models.PositiveSmallIntegerField()),
                ('signal', models.CharField(choices=[('Ia', 'Phase A current'), ('Ib', 'Phase B current'), ('Ic', 'Phase C current'), ('Va', 'Phase A voltage'), ('Vb', 'Phase B voltage'), ('Vc', 'Phase C voltage'), ('-', 'None')], default='-', max_length=2)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_channels', to='comtrade_reader.file')),
            ],
            options={
                'unique_together': {('file', 'comtrade_channel_id')},
            },
        ),
    ]
