# Generated by Django 5.1 on 2024-08-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0003_analogchannel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analogchannel',
            old_name='comtrade_channel_id',
            new_name='channel_id',
        ),
        migrations.AlterUniqueTogether(
            name='analogchannel',
            unique_together={('file', 'channel_id')},
        ),
        migrations.AddField(
            model_name='analogchannel',
            name='channel_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
