# Generated by Django 5.1 on 2024-08-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0004_rename_comtrade_channel_id_analogchannel_channel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analogchannel',
            name='pors',
            field=models.CharField(default='P', max_length=1),
            preserve_default=False,
        ),
    ]
