# Generated by Django 5.1 on 2024-08-21 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0005_analogchannel_pors'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='analogchannel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='analogchannel',
            name='comtrade_channel_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
