# Generated by Django 5.1 on 2024-08-21 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0007_alter_analogchannel_channel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalChannel',
            fields=[
                ('channel_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('comtrade_channel_id', models.IntegerField()),
                ('channel_name', models.CharField(default='', max_length=10)),
                ('normal_state', models.PositiveSmallIntegerField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_channels', to='comtrade_reader.file')),
            ],
        ),
    ]
