# Generated by Django 5.1 on 2024-08-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0008_digitalchannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalchannel',
            name='channel_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
