# Generated by Django 5.1 on 2024-08-21 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0009_alter_digitalchannel_channel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalogSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_value', models.DecimalField(decimal_places=6, max_digits=8)),
                ('ia_value', models.DecimalField(decimal_places=6, max_digits=8)),
                ('ib_value', models.DecimalField(decimal_places=6, max_digits=8)),
                ('ic_value', models.DecimalField(decimal_places=6, max_digits=8)),
                ('va_value', models.DecimalField(decimal_places=6, max_digits=8)),
                ('vb_value', models.DecimalField(decimal_places=6, max_digits=8)),
                ('vc_value', models.DecimalField(decimal_places=6, max_digits=8)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_signals', to='comtrade_reader.file')),
            ],
        ),
    ]
