# Generated by Django 5.1 on 2024-08-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0010_analogsignal'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ia_channel_id',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='file',
            name='ib_channel_id',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='file',
            name='ic_channel_id',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='file',
            name='va_channel_id',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='file',
            name='vb_channel_id',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='file',
            name='vc_channel_id',
            field=models.PositiveSmallIntegerField(default=6),
        ),
    ]
