# Generated by Django 5.1 on 2024-08-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0011_file_ia_channel_id_file_ib_channel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='ia_channel_id',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='ib_channel_id',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='ic_channel_id',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='va_channel_id',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='vb_channel_id',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='vc_channel_id',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
