# Generated by Django 5.1 on 2024-08-21 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0012_alter_file_ia_channel_id_alter_file_ib_channel_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analogchannel',
            name='signal',
        ),
    ]
