# Generated by Django 5.1 on 2024-08-21 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0013_remove_analogchannel_signal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analogsignal',
            name='time_value',
        ),
        migrations.CreateModel(
            name='TimeSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_value', models.DecimalField(decimal_places=6, max_digits=8)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_signals', to='comtrade_reader.file')),
            ],
        ),
    ]
