# Generated by Django 5.1 on 2024-08-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0014_remove_analogsignal_time_value_timesignal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analogsignal',
            name='ia_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='analogsignal',
            name='ib_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='analogsignal',
            name='ic_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='analogsignal',
            name='va_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='analogsignal',
            name='vb_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='analogsignal',
            name='vc_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='timesignal',
            name='time_value',
            field=models.FloatField(),
        ),
    ]
