# Generated by Django 5.1 on 2024-08-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0015_alter_analogsignal_ia_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesignal',
            name='file',
        ),
        migrations.DeleteModel(
            name='AnalogSignal',
        ),
        migrations.DeleteModel(
            name='TimeSignal',
        ),
    ]
