# Generated by Django 5.1 on 2024-08-29 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0017_rename_comtrade_channel_id_analogchannel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='ia_channel_id',
        ),
        migrations.RemoveField(
            model_name='file',
            name='ib_channel_id',
        ),
        migrations.RemoveField(
            model_name='file',
            name='ic_channel_id',
        ),
        migrations.RemoveField(
            model_name='file',
            name='va_channel_id',
        ),
        migrations.RemoveField(
            model_name='file',
            name='vb_channel_id',
        ),
        migrations.RemoveField(
            model_name='file',
            name='vc_channel_id',
        ),
        migrations.CreateModel(
            name='SelectChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField()),
                ('channel_type', models.CharField(choices=[('A', 'Analog'), ('D', 'Digital')], default='A', max_length=1)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_analog_channels', to='comtrade_reader.file')),
            ],
        ),
    ]
