# Generated by Django 5.1 on 2024-08-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0018_remove_file_ia_channel_id_remove_file_ib_channel_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelectChannels',
            new_name='SelectChannel',
        ),
    ]
