# Generated by Django 5.1 on 2024-08-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0019_rename_selectchannels_selectchannel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectChannel',
        ),
    ]
