# Generated by Django 5.1 on 2024-08-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0020_delete_selectchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='analogchannel',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='digitalchannel',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
