# Generated by Django 5.1 on 2024-08-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0021_analogchannel_selected_digitalchannel_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='digitalchannel',
            old_name='comtrade_channel_id',
            new_name='id',
        ),
    ]
