# Generated by Django 5.1 on 2024-09-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0022_rename_comtrade_channel_id_digitalchannel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
