# Generated by Django 5.1.1 on 2024-09-11 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0023_project_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalogSignals',
            fields=[
                ('sample_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('time_signal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ia_signal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ib_signal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ic_signal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('va_signal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vb_signal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vc_signal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_signals', to='comtrade_reader.file')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalSignals',
            fields=[
                ('sample_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('time_signal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('d1_signal', models.PositiveSmallIntegerField()),
                ('d2_signal', models.PositiveSmallIntegerField()),
                ('d3_signal', models.PositiveSmallIntegerField()),
                ('d4_signal', models.PositiveSmallIntegerField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_signals', to='comtrade_reader.file')),
            ],
        ),
    ]
