# Generated by Django 5.1.1 on 2024-09-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0024_analogsignals_digitalsignals'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ia_channel',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='file',
            name='ib_channel',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='file',
            name='ic_channel',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='file',
            name='va_channel',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='file',
            name='vb_channel',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='file',
            name='vc_channel',
            field=models.CharField(default='', max_length=10),
        ),
    ]
