# Generated by Django 5.1.1 on 2024-09-11 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0025_file_ia_channel_file_ib_channel_file_ic_channel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnalogSignals',
            new_name='AnalogSignal',
        ),
        migrations.RenameModel(
            old_name='DigitalSignals',
            new_name='DigitalSignal',
        ),
    ]
