# Generated by Django 5.1.1 on 2024-09-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0026_rename_analogsignals_analogsignal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analogsignal',
            name='time_signal',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='digitalsignal',
            name='time_signal',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
    ]
