# Generated by Django 5.1.1 on 2024-09-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0027_alter_analogsignal_time_signal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='d1_channel',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='file',
            name='d2_channel',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='file',
            name='d3_channel',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='file',
            name='d4_channel',
            field=models.CharField(default='', max_length=10),
        ),
    ]
