# Generated by Django 5.1.1 on 2024-09-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0028_file_d1_channel_file_d2_channel_file_d3_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='d1_channel',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='d2_channel',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='d3_channel',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='d4_channel',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='ia_channel',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='ib_channel',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='ic_channel',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='va_channel',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='vb_channel',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='vc_channel',
            field=models.CharField(default='', max_length=20),
        ),
    ]
