# Generated by Django 5.1.1 on 2024-09-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0029_alter_file_d1_channel_alter_file_d2_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analogsignal',
            name='sample_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='digitalsignal',
            name='sample_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
