# Generated by Django 5.1.1 on 2024-09-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0030_alter_analogsignal_sample_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analogsignal',
            name='ia_signal',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='analogsignal',
            name='ib_signal',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='analogsignal',
            name='ic_signal',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='analogsignal',
            name='va_signal',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='analogsignal',
            name='vb_signal',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
        migrations.AlterField(
            model_name='analogsignal',
            name='vc_signal',
            field=models.DecimalField(decimal_places=6, max_digits=10),
        ),
    ]
