# Generated by Django 5.1.1 on 2024-09-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0032_alter_analogsignal_ia_signal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='d1_channel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='d2_channel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='d3_channel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='d4_channel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='ia_channel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='ib_channel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='ic_channel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='va_channel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='vb_channel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='file',
            name='vc_channel',
            field=models.CharField(default='', max_length=50),
        ),
    ]
