# Generated by Django 5.1.1 on 2024-09-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0033_alter_file_d1_channel_alter_file_d2_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analogchannel',
            name='channel_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='analogchannel',
            name='channel_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='digitalchannel',
            name='channel_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
