# Generated by Django 5.1.1 on 2024-09-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0034_alter_analogchannel_channel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analogsignal',
            name='time_stamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='analogsignal',
            name='ia_signal',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='analogsignal',
            name='ib_signal',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='analogsignal',
            name='ic_signal',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='analogsignal',
            name='va_signal',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='analogsignal',
            name='vb_signal',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='analogsignal',
            name='vc_signal',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
