# Generated by Django 5.1.1 on 2024-09-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0035_analogsignal_time_stamp_alter_analogsignal_ia_signal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analogsignal',
            name='time_stamp',
            field=models.CharField(default='', max_length=50),
        ),
    ]
