# Generated by Django 5.1.1 on 2024-09-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0036_alter_analogsignal_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analogchannel',
            name='primary',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='analogchannel',
            name='secondary',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
