# Generated by Django 5.1.1 on 2024-09-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0037_alter_analogchannel_primary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analogchannel',
            name='primary',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='analogchannel',
            name='secondary',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
