# Generated by Django 5.1.2 on 2024-12-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0038_alter_analogchannel_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analogsignal',
            name='in_signal',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='file',
            name='in_channel',
            field=models.CharField(default='', max_length=50),
        ),
    ]
