# Generated by Django 5.1.2 on 2025-01-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0039_analogsignal_in_signal_file_in_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalsignal',
            name='d10_signal',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='digitalsignal',
            name='d11_signal',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='digitalsignal',
            name='d12_signal',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='digitalsignal',
            name='d5_signal',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='digitalsignal',
            name='d6_signal',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='digitalsignal',
            name='d7_signal',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='digitalsignal',
            name='d8_signal',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='digitalsignal',
            name='d9_signal',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='d10_channel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='file',
            name='d11_channel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='file',
            name='d12_channel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='file',
            name='d5_channel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='file',
            name='d6_channel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='file',
            name='d7_channel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='file',
            name='d8_channel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='file',
            name='d9_channel',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='digitalsignal',
            name='d1_signal',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='digitalsignal',
            name='d2_signal',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='digitalsignal',
            name='d3_signal',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='digitalsignal',
            name='d4_signal',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
