# Generated by Django 5.1.2 on 2025-02-03 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0040_digitalsignal_d10_signal_digitalsignal_d11_signal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalogSignalResampled',
            fields=[
                ('sample_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('time_signal', models.DecimalField(decimal_places=6, max_digits=8)),
                ('ia_signal', models.DecimalField(decimal_places=6, max_digits=12)),
                ('ib_signal', models.DecimalField(decimal_places=6, max_digits=12)),
                ('ic_signal', models.DecimalField(decimal_places=6, max_digits=12)),
                ('in_signal', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('va_signal', models.DecimalField(decimal_places=6, max_digits=12)),
                ('vb_signal', models.DecimalField(decimal_places=6, max_digits=12)),
                ('vc_signal', models.DecimalField(decimal_places=6, max_digits=12)),
                ('time_stamp', models.CharField(default='', max_length=50)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_signals_resampled', to='comtrade_reader.file')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalSignalResampled',
            fields=[
                ('sample_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('time_signal', models.DecimalField(decimal_places=6, max_digits=8)),
                ('d1_signal', models.PositiveSmallIntegerField(default=0)),
                ('d2_signal', models.PositiveSmallIntegerField(default=0)),
                ('d3_signal', models.PositiveSmallIntegerField(default=0)),
                ('d4_signal', models.PositiveSmallIntegerField(default=0)),
                ('d5_signal', models.PositiveSmallIntegerField(default=0)),
                ('d6_signal', models.PositiveSmallIntegerField(default=0)),
                ('d7_signal', models.PositiveSmallIntegerField(default=0)),
                ('d8_signal', models.PositiveSmallIntegerField(default=0)),
                ('d9_signal', models.PositiveSmallIntegerField(default=0)),
                ('d10_signal', models.PositiveSmallIntegerField(default=0)),
                ('d11_signal', models.PositiveSmallIntegerField(default=0)),
                ('d12_signal', models.PositiveSmallIntegerField(default=0)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_signals_resampled', to='comtrade_reader.file')),
            ],
        ),
    ]
