# Generated by Django 5.1.2 on 2025-02-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0041_analogsignalresampled_digitalsignalresampled'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='resampled_frequency',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
