# Generated by Django 5.1.2 on 2025-02-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0042_file_resampled_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analogsignal',
            name='va_signal',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='analogsignal',
            name='vb_signal',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='analogsignal',
            name='vc_signal',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
    ]
