# Generated by Django 5.1.2 on 2025-02-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0043_alter_analogsignal_va_signal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analogsignal',
            name='ia_signal',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='analogsignal',
            name='ib_signal',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='analogsignal',
            name='ic_signal',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='analogsignal',
            name='in_signal',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
    ]
