# Generated by Django 5.1.2 on 2025-03-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comtrade_reader', '0044_alter_analogsignal_ia_signal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analogsignalresampled',
            name='ia_signal',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='analogsignalresampled',
            name='ib_signal',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='analogsignalresampled',
            name='ic_signal',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='analogsignalresampled',
            name='in_signal',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='analogsignalresampled',
            name='va_signal',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='analogsignalresampled',
            name='vb_signal',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
        migrations.AlterField(
            model_name='analogsignalresampled',
            name='vc_signal',
            field=models.DecimalField(decimal_places=6, max_digits=20),
        ),
    ]
